# Generated by Django 5.2.7 on 2026-01-16 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_city_itemrequest_city_place_itemrequest_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='item.item')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('item', 'name')},
            },
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='item.itemcolor'),
        ),
        migrations.CreateModel(
            name='ItemColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_color_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.itemcolor')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
