# Generated by Django 5.2.13 on 2026-04-10 11:27

import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_itemcolor_itemrequest_color_itemcolorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolor',
            name='hex_code',
            field=models.CharField(blank=True, default='', help_text='Optional display swatch, e.g. #4B0082', max_length=7, validators=[item.models.validate_optional_hex]),
        ),
    ]
